language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  # 3.7 is NOT supported yet
  # - "3.7-dev"  # 3.7 development branch

install:
  - pip install fabric3 virtualenv

script:
  - echo "Data Mining" | make
